default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
        additional_dependencies:
          - git+https://github.com/Me-Phew/cz-conventional-commits-jira-optional.git@main

  - hooks:
      - id: gitleaks
    repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2

  - hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^.*\.vscode/\S*.json$
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        exclude: ^.*\.lock$
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-ast
      - id: debug-statements
      - id: check-builtin-literals
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0

  - hooks:
      - args:
          - --fix
        id: ruff
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0

  - hooks:
      - entry: uvx ty check
        files: ^src/simple485_remastered/.*\.py$
        id: typecheck
        language: system
        name: Typecheck
        types:
          - python
    repo: local
